name: Sanity checker

on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git config core.filemode true
          if [[  $(git diff master..HEAD -p -R --no-ext-diff --no-color | grep -E "^(old mode)" -B1 -A1 --color=never | grep -E "^(diff|(old|new) mode)" --color=never | wc -l) -ne 0 ]]
          then
              echo "please fix filemode issues"
              echo "run: git diff master..HEAD -p -R --no-ext-diff --no-color | grep -E \"^(old mode)\" -B1 -A1 --color=never | grep -E \"^(diff|(old|new) mode)\" --color=never | git apply --cached"
              echo "commit the changes after running the above command"
              echo "after committing and pushing, please run git config core.filemode false to avoid such issues in future"
              exit 1
          fi
          git config core.filemode false
          git config core.autoclrf true
          git add --renormalize .
          if [[  $(git diff --staged | tail | wc -l) -ne 0 ]]
          then
              echo "linux and windows clrf issues found"
              echo "please run git config core.autoclrf true and then git add --renormalize ." 
              exit 1
          fi
          echo "All checks passed!"
